version: "3.8"
services:
  status:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: status
    restart: always
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 6M
        reservations:
          cpus: '0.1'
          memory: 6M
