version: "3.8"
services:
  status:
    # image: "devops-webapp-python:latest"
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: status
    restart: always
    ports:
      - "8000:8000"
