name: Manual Dispatch Workflow

on:
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  helm_list:
    runs-on: self-hosted
    environment: github-dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo a message
      run: echo "Hello, this is a message from your self-hosted runner!"

    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # TenantId of the Azure Service principal created.
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # Azure subscriptionId
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v3
      with:
        # Resource Group Name
        resource-group: dvopla-d-itn-dev-aks-rg
        # AKS Cluster Name
        cluster-name: dvopla-d-itn-dev-aks
        # AKS Cluster Subscription
        subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # Get cluster admin credentials. Values: true or false
        admin: false
        # Enables kubelogin for non-admin user scenario. Values: true or false
        use-kubelogin: true

    - name: Helm tool installer
      uses: Azure/setup-helm@v3

    - run: helm list



